apiVersion: v1
kind: Service
metadata:
  name: cc5550
  labels:
    app: todo
spec:
  selector:
    app: todo
    tier: web
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  loadBalancerIP: "35.231.34.19"
